<template>
    <main>

        <Header />
        <!-- Security Controls & Risk Assessment -->
<section class="py-5">
  <div class="container">
    <div class="row g-4 align-items-center">
      <div class="col-lg-6">
        <img src="https://img.freepik.com/free-vector/information-security-illustration_114360-4984.jpg?w=826" alt="Security Controls" class="img-fluid img-rounded">
      </div>
      <div class="col-lg-6">
        <div class="info-block">
          <h2>Implementing Security Controls:</h2>
          <p>With guidance from your AI mentor, you’ll learn to design, implement, and assess security controls within simulated organizations, following industry frameworks like NIST, ISO 27001, and SOC 2.</p>
          <p class="feature-title">Risk Assessment and Management:</p>
          <p>Your AI mentor will train you to identify, evaluate, and mitigate information security risks. You’ll conduct risk assessments and develop risk management plans, often interacting with AI clients to mirror real-world consulting scenarios.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Audit, Policy & Incident Response -->
<section class="highlight-section">
  <div class="container">
    <div class="row g-4 align-items-center">
      <div class="col-lg-6 order-lg-2">
        <img src="https://img.freepik.com/free-vector/audit-concept-illustration_114360-9245.jpg?w=826" alt="Audit & Policy" class="img-fluid img-rounded">
      </div>
      <div class="col-lg-6">
        <div class="info-block">
          <h2>Audit and Compliance:</h2>
          <p>Gain hands-on experience preparing for and managing compliance audits. Work with AI clients to ensure adherence to regulatory requirements and data privacy laws, just as you would with real organizations.</p>
          <p >Policy Development:</p>
          <p>Develop and review security policies and governance documents with the support of your AI mentor, ensuring alignment with business objectives and regulatory standards.</p>
          <p >Incident Response:</p>
          <p>Practice responding to simulated cybersecurity incidents generated by AI clients, including documentation, reporting, and continuous process improvement.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Real-World Projects -->
<section class="py-5">
  <div class="container">
    <div class="row g-4 align-items-center">
      <div class="col-lg-6">
        <img src="https://img.freepik.com/free-vector/project-management-business-multitasking-agile-development-business-team-planning-collaboration-task-organization-efficiency-concept_335657-2601.jpg?w=826" alt="Real-World Projects" class="img-fluid img-rounded">
      </div>
      <div class="col-lg-6">
        <div class="info-block">
          <h2 class="">Real-World Projects and Practical Experience</h2>
          <p class="feature-title">Case Studies and Simulations:</p>
          <p>Work through real-world projects, tackling challenges presented by AI clients—such as risk assessments, compliance gap analyses, and audit preparations.</p>
          <p class="feature-title">Client Projects:</p>
          <p>Engage in consulting projects for AI clients that replicate real business environments. Apply your skills to solve authentic challenges like developing compliance roadmaps, conducting security assessments, or supporting audit processes.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- Consulting Exposure & Portfolio -->
<section class="highlight-section">
  <div class="container">
    <div class="row g-4 align-items-center">
      <div class="col-lg-6 order-lg-2">
        <img src="https://img.freepik.com/free-vector/personal-portfolio-concept-illustration_114360-4576.jpg?w=826" alt="Portfolio" class="img-fluid img-rounded">
      </div>
      <div class="col-lg-6">
        <div class="info-block">
          <h2>Exposure to Consulting Practices:</h2>
          <p>Learn consulting fundamentals such as client communication, presentation skills, and structured problem-solving through direct involvement with AI clients in projects.</p>
          <p>Portfolio Development:</p>
          <p>Build a portfolio of completed projects, reports, and deliverables, all generated from your interactions with AI mentors and AI clients—demonstrating your expertise to future employers or clients.</p>
        </div>
      </div>
    </div>
  </div>
</section>



        <div>
            <Footer />
        </div>

    </main>
</template>

<script lang="ts">
import Footer from '@/components/Footer.vue';
import Header from '@/components/Header.vue';

export default{
    name: "ExperienceGainView",
    components: {Header , Footer}
}

</script>


<style>
    .section-heading {
      color: #007BAF;
      font-size: 2.3rem;
      font-weight: bold;
    }
    .info-block {
      background-color: #fff;
      padding: 30px;
      border-radius: 10px;
      box-shadow: 0 4px 20px rgba(0, 0, 0, 0.06);
    }
    .info-block p{
        font-size: 17px;
        font-weight: 400;
        color: black;
    }
    .info-block h2{
        color: #007BAF;
    }
    .highlight-section {
      background-color: #f8f9fa;
      padding: 60px 0;
    }
    .img-rounded {
      border-radius: 12px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.08);
    }
    /* .feature-title {
      font-size: 1.25rem;
      font-weight: 400;
      font-size: 17px;
      color: black;
    } */
  </style>